### ISSUE TITLE
flex水平垂直居中

### ISSUE THREAD

**Issue by cgzero** [cgzero/tech-note#10]
```css
.foo {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

关于justify-content的几个属性
![](https://raw.githubusercontent.com/cgzero/tech-note/master/img/10/justify-content.png)

关于align-items
![](https://raw.githubusercontent.com/cgzero/tech-note/master/img/10/align-items.png)
