### ISSUE TITLE
不确定宽高的图片水平垂直居中（IE6、IE7无效）

### ISSUE THREAD

**Issue by cgzero** [cgzero/tech-note#13]
```html

<div><img></div>

```

```css

div {
	width: 100px;
	height: 100px;
	display: table-cell;
	vertical-align: middle;
	text-align: center;
	/* IE：利用font-size属性产生的行高 */
	*font-size: 100 * 0.873px;
	/* 防止非utf-8引起的hack失效问题，如gbk编码 */
	*font-family:Arial;
}

img {
	vertical-align: middle;
}

```
