### ISSUE TITLE
ie hack整理

### ISSUE THREAD

**Issue by cgzero** [cgzero/tech-note#25]
```css
div {
    _color:red; /* ie6 */
    *color:black;_color:red; /* ie7 */
    *color:red; /* ie6 - ie7 */
    color:red\9; /* ie6 - ie newset */
    color:red\9;_color:#ccc; /* ie7 - ie newset */
    color:red\9;*color:black; /* ie8 - ie newset */
}
```

```css
/* inline-block实现方法 */
div {
	display: inline-block; /* 现代浏览器和IE6、7 inline 元素 */
	*display: inline; /* IE6、7 block 元素 */
	*zoom: 1;
}
```

```css
/* min-height实现方法 */
div {
	height:auto !important;	
	height:100px; /* IE6以及IE诡异模式下相当于min-height，内容会撑大元素 */
	min-height:100px;
}
```

```css
/* 清除浮动 */
.clearfix:after {
	content:" ";
	display:block;
	height:0;
	clear:both;
	visibility: hidden;
}
.clearfix { zoom: 1; }
```
